### ISSUE TITLE
Help build error

### ISSUE THREAD

**Issue by skyworldp** [RinoRika/Reversal#1]
when i try to build it.
it shows i am lack of JAVACV.
and there are some wrong pointed methods in the sourse

**Comment by skyworldp** [comment]
it seemed i use the newer version of the oshi.jar

**Comment by Stars-Azusa** [comment]
Sorry, the javacv code is deprecated but i forgot to delete it. You can simply delete videoplayer.kt. It will be removed in the next update.

**Comment by Stars-Azusa** [comment]
please let me know if your problem is resolved, thx.
